### ISSUE TITLE
Contract Call example code broken

### ISSUE THREAD

**Issue by Steven-Rowell** [neo-project/docs#104]
I was testing out the contract call functionality and found the example in the documentation to be broken. I won't suggest any edits because I am still unable to get it to work. I beleive however the decorator should be something like:

```
[Appcall("XXX")] //hash
public static extern bool AnotherContract();
```
However my following example produces an error.
```


    public class Contract1 : VerificationCode
    {
        [Appcall("xxxxxx")]//hash
        public static extern bool AnotherContract(int arg1);

        public static bool Verify(byte[] arg1)
        {

            Runtime.Log("In Main");
            AnotherContract(1);
            return true;
        }
    }

```

> CONVERTTASK : Convert error : System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by canesin** [comment]
@lllwvlvwlll or @vardthomas could you take a look at this ?

**Comment by erikzhang** [comment]
@lightszero

**Comment by erikzhang** [comment]
It seems you need to replace the "xxxxxx" to a script hash. @Steven-Rowell

**Comment by Steven-Rowell** [comment]
@erikzhang I omitted the script hash to generalize the example.

**Comment by Steven-Rowell** [comment]
![image](https://user-images.githubusercontent.com/18665547/29322152-89987224-81aa-11e7-8163-4b4391142af9.png)

**Comment by erikzhang** [comment]
Script hash is a 20 bytes length array (40 hex characters)

**Comment by Steven-Rowell** [comment]
Sorry! For the above example it would be 
`42d94fc9e85552cde166c4c1b838374c3b776492`
Which I initially tried. I have the contract deployed on a private chain.

**Comment by lightszero** [comment]
we had fix it.pull and try it again.

**Comment by Steven-Rowell** [comment]
@lightszero It's compiling now! However, every attempt I've made at a contract call fails with 
![image](https://user-images.githubusercontent.com/18665547/29427911-4fc241aa-8359-11e7-8f06-4b56b4e80190.png).

Additionally my debug console print lines execute in the calling contract both before and after the contract call, but not in the called contract.
