### ISSUE TITLE
neo3 docs suggestions

### ISSUE THREAD

**Issue by nicolegys** [neo-project/docs#1068]

**Comment by nicolegys** [comment]
【查看区块链】
![Uploading image.png…]()

**Comment by nicolegys** [comment]
【钱包操作】
1.最好说明一下，不要将钱包文件放在gui的安装目录下
2.已支持
![image](https://user-images.githubusercontent.com/43694095/80558245-44fea080-8a0c-11ea-9a12-ded43423b6d7.png)
3.钱包中的所有资产类型和余额总量
![image](https://user-images.githubusercontent.com/43694095/80559175-4aa9b580-8a0f-11ea-8fe6-c3e565a93a13.png)

**Comment by nicolegys** [comment]
【合约】
1.不支持ID搜索，不显示发行时间
![image](https://user-images.githubusercontent.com/43694095/80563685-5355b800-8a1e-11ea-8c68-5680c43c717f.png)
2.不支持
![image](https://user-images.githubusercontent.com/43694095/80563766-96179000-8a1e-11ea-812f-85829213b5dc.png)

**Comment by wanglongfei88** [comment]
fixed
