### ISSUE TITLE
Hyperlink failure

### ISSUE THREAD

**Issue by ProDog** [neo-project/docs#1077]
Page: https://docs.neo.org/tutorial/zh-cn/5-network/1-Introduction_to_the_NEO_network_protocol.html
Broken link:

![image](https://user-images.githubusercontent.com/12728872/83385405-c1c1d780-a41b-11ea-8c1b-8b935bf96d25.png)

![image](https://user-images.githubusercontent.com/12728872/83385427-cf775d00-a41b-11ea-9f33-e90b22ded719.png)

![image](https://user-images.githubusercontent.com/12728872/83385462-ddc57900-a41b-11ea-9e07-5500908ae849.png)

![image](https://user-images.githubusercontent.com/12728872/83385551-08afcd00-a41c-11ea-90bb-127381edcbb3.png)

**Comment by ProDog** [comment]
Page: https://docs.neo.org/docs/zh-cn/node/python/overview.html
Broken link:

![image](https://user-images.githubusercontent.com/12728872/83414650-6fe77480-a450-11ea-9e4c-0b4a2c15c0e8.png)

**Comment by Celia18305** [comment]
https://github.com/neo-project/docs/pull/1079
