### ISSUE TITLE
Getrawmempool RPC call documentation is outdated

### ISSUE THREAD

**Issue by roman-khimov** [neo-project/docs#1108]
**Describe the bug**
Current getrawmempool documentation doesn't mention its boolean parameter and alternative (extended) response format:
https://docs.neo.org/v3/docs/en-us/reference/rpc/latest-version/api/getrawmempool.html

**Expected behavior**
Documentation should be in sync with implementation.

**(Optional) Additional context**
I'm not sure if it's appropriate to submit documentation bugs here (as documentation is not maintained here), if there are better places/formats please tell me.

**Comment by Celia18305** [comment]
Fixed in https://github.com/neo-project/docs/pull/1107
