### ISSUE TITLE
Add missing RPC call to documentation

### ISSUE THREAD

**Issue by ixje** [neo-project/docs#1138]
https://github.com/neo-project/neo-modules/pull/243 introduced a new RPC call `getunclaimedgas` that is not described in the NEO3 documentation on docs.neo.org. Because it is missing in the documentation I even unnecessarily created a issue for it https://github.com/neo-project/neo-modules/issues/360

**Comment by fabwa** [comment]
https://docs.neo.org/v3/docs/en-us/reference/rpc/latest-version/api/getunclaimedgas.html
