### ISSUE TITLE
Supported languages incorrect

### ISSUE THREAD

**Issue by kekearif** [neo-project/docs#117]
The document states:

The languages that are currently supported are:

C#, VB.Net, F#
Java, Kotlin

This is simply not true. Java is not supported. Kotlin is not supported. Only c# is supported.

**Comment by canesin** [comment]
JVM compiler: https://github.com/neo-project/neo-compiler/tree/master/neoj
Getting started with Java: http://docs.neo.org/zh-cn/sc/getting-started-java.html

for most up to date docs always refer to mandarin.
