### ISSUE TITLE
Dead Tutorial link for V3

### ISSUE THREAD

**Issue by fabwa** [neo-project/docs#1202]
https://docs.neo.org/v3/tutorial/en-us/index.html

@Celia18305

**Comment by steven1227** [comment]
@fabwa We will fix this soon

**Comment by fabwa** [comment]
@steven1227 iirc this was fixed already by pointing to ; but i merged a couple more fixes to the neo3 branch. please have a look

**Comment by steven1227** [comment]
> @steven1227 iirc this was fixed already by pointing to ; but i merged a couple more fixes to the neo3 branch. please have a look

Sure, we will @fabwa
