### ISSUE TITLE
Need to replace onPayment with onNEP17Payment

### ISSUE THREAD

**Issue by denissuslov** [neo-project/docs#1272]
onPayment was replaced by onNEP17Payment

Correct here: https://docs.neo.org/docs/en-us/develop/write/nep17.html

But when click "NEP-17 contract code" forwards to 
https://github.com/neo-project/examples/blob/37487a324b4be695af422f37d668e15a05d75e1e/csharp/NEP17/NEP17.Methods.cs
where it's onPayment in NEP17.Methods.cs

**Comment by Celia18305** [comment]
The link was updated
