### ISSUE TITLE
Neo-CLI How to reconcile the differences between the docs and project README

### ISSUE THREAD

**Issue by CodeMonkeyMike** [neo-project/docs#129]
The installation steps for Neo-CLI are either more specific or no longer correct in the documentation as compared to the README of the Neo-CLI repository. I would assume that it would be best to keep specific installation instructions on the Neo-CLI repositories README and to remove the instructions from the Documentation.

https://github.com/neo-project/docs/blob/master/en-us/node/setup.md#installation-of-neo-node
https://github.com/neo-project/neo-cli

**Comment by Celia18305** [comment]
The Neo-CLI README is intended to provide brief information for developers to compile the Neo-CLI, while the installation document is the offical installation instructions published on http://docs.neo.org/en-us/node/setup.html for all users. They are not the same.
