### ISSUE TITLE
Could not use search on the main page

### ISSUE THREAD

**Issue by carpawell** [neo-project/docs#1298]
Typing "validator"(just an example) in search returns empty array result("No results found").

It sends `GET` request with `https://docs.neo.org/?k=validator&l=ru` request URL in my case.

It seems that `l=ru` should be `l=en`. In that case, it returns actual results.

However, I got such problems in `Chrome` only(PC and android), with `Firefox` it works just fine.

My devices:
- `Android` 10, `Chrome` 92.0.4515.115
- `Ubuntu` 20.04.2 LTS, `Chrome` 92.0.4515.107
- `Ubuntu` 20.04.2 LTS, `Firefox` 87.0

**Comment by chenzhitong** [comment]
fixed, thanks
