### ISSUE TITLE
Kotlin demo

### ISSUE THREAD

**Issue by Sjors** [neo-project/docs#132]
It would be useful to have a Hello World smart contract example for Kotlin, including instructions how to deploy to the blockchain. For many Linux & Mac developers this is probably much easier than learning C#, VB.Net or F#.

**Comment by wy** [comment]
@erikzhang Since Kotlin compiles to Java bytecode we can re-use the neoj compiler right?

Could you create an examples-kotlin that I can fork and commit the Hello World examples?

Thanks

**Comment by wy** [comment]
@Sjors I've got a Hello World example here: https://github.com/wy/examples-kotlin/blob/master/HelloWorld.kt

If you are using the NEO Developer GUI you can try invoking the function (Script Hash) 5e3070f4af32a3e0cf001646768b5912bb423f02 and it will return back "Hello World"

**Comment by Sjors** [comment]
@wy thanks, is there a way to do that without the GUI? I'm more of a command line kind of person :-)

**Comment by wy** [comment]
I'm sure there will be but at the moment I don't know if command line outputs return values, haven't checked and this was only a feature in the Developer BETA GUI not the main GUI.

**Comment by erikzhang** [comment]
@wy If you agree, I can transfer the repo to neo-project.

**Comment by wy** [comment]
@erikzhang yes, ready. Thanks

**Comment by erikzhang** [comment]
@wy You need to invite me to the repo as an admin, then I can transfer it to here.

**Comment by wy** [comment]
HelloWorld example now here.

https://github.com/neo-project/examples-kotlin

Should we close this yet or wait until we can port all of the examples over?

**Comment by Sjors** [comment]
Thanks! I'll close this.
