### ISSUE TITLE
N3 invokecontractverify RPC method incorrect parameter description

### ISSUE THREAD

**Issue by ixje** [neo-project/docs#1327]
The documentation states that the `params` argument must be an empty array
```
params: The parameters to be passed to the smart contract operation. It must be an empty array [] as by default Neo only accepts the verify function without parameter.
```

The code actually allows for parameters
https://github.com/neo-project/neo-modules/blob/9d1166a86309a54095b595a27b49fba2c850c864/src/RpcServer/RpcServer.Wallet.cs#L334

**Comment by Celia18305** [comment]
Fixed in PR #1348
