### ISSUE TITLE
docs.neo.org Does Not Display Correctly

### ISSUE THREAD

**Issue by anfn101** [neo-project/docs#168]
docs.neo.org has stopped displaying the left navigation bar. Furthermore, the left navigation bar did not update before when it was still working in response to new documents being merged (two days ago).

Example:
![screen shot 2017-09-12 at 9 31 49 pm](https://user-images.githubusercontent.com/26677979/30355519-e94bbe48-9801-11e7-8301-3d68a33ca55e.png)

**Comment by anfn101** [comment]
You also see a strange overlap in cases where the list is long on the right side. (See the "return to top link overlapping at bottom)

![screen shot 2017-09-12 at 9 33 18 pm](https://user-images.githubusercontent.com/26677979/30355545-0c7883d8-9802-11e7-9d74-dc51ff3da5bc.png)

**Comment by erikzhang** [comment]
repaired
