### ISSUE TITLE
Unable to compile project in VS 2017 Pro, Enterprise and Community

### ISSUE THREAD

**Issue by tcsekhar** [neo-project/docs#179]
The interface for the Contract1 in the NeoContract template is different from what the documentation says. Doesn't matter which interface I change it to, that interface is not implemented and I get a compile error.

Error	CS0246	The type or namespace name 'Framework' could not be found (are you missing a using directive or an assembly reference?)	NeoContract	\Projects\neo-compiler-master\NeoContract\Contract1.cs	8	Active

**Comment by notatestuser** [comment]
Did you restore nuget packages and check that `SmartContract` is being imported properly? There's no need for the Framework. part in `Framework.SmartContract`

**Comment by PeterLinX** [comment]
Delete Framework and try again.
