### ISSUE TITLE
Clarification on docs for exchange developers: sys_fee, net_fee, gas

### ISSUE THREAD

**Issue by metachris** [neo-project/docs#260]
There have been a few questions by exchange developers about the docs for exchange developers: https://github.com/neo-project/docs/blob/master/en-us/exchange.md#rpc-method-sendtoaddress

Could you please clarify the following questions, regarding the `InvocationTransaction` response:

* What is the difference between the three fields: `sys_fee`, `net_fee`, `gas`?
* What will happen if `sys_fee` is not enough for running contract?
* Which error cases are possible when invoking `sendtoaddress`?

cc/ @erikzhang

**Comment by anfn101** [comment]
Any update? @PeterLinX @erikzhang

**Comment by fabwa** [comment]
inactivity
