### ISSUE TITLE
Private Chain - After Broadcast Transaction not credited

### ISSUE THREAD

**Issue by VaduganathanPillappan** [neo-project/docs#272]
Hi, I have established a private chain and was able to get  the initial 100 million NEO into my contract address. I tried to transfer the NEO's to one of my 4 wallet's and done all signature process until Broadcast.
Its been an hr but no luck transferring the NEO. In the transaction histroy I can see one transaction.
Am I missing something!!!

Thanks!
Vaduganathan

![image](https://user-images.githubusercontent.com/32697208/34411558-58a5e5ee-ebfd-11e7-92af-b26cf2eb9ecc.png)

**Comment by jonatanblockchain** [comment]
Height is 0. You are not connected to any host. Did you create the private-chain using a CoZ docker image?

**Comment by VaduganathanPillappan** [comment]
I am very new to block chain, trying to understand from document available in neo wesite. I used Neo-Cli on four private servers and started consensus.
I used Neo-GUI for transfer of NEo

**Comment by jonatanblockchain** [comment]
Try:

1- Ping consensus node's between consensus node.
2- Ping consensus node's from the neo-gui host.
3- Close neo-gui, delete chain folder and peers.dat and start neo-gui

**Comment by VaduganathanPillappan** [comment]
1 and 2 were success - 0% loss
3rd did not help

**Comment by VaduganathanPillappan** [comment]
Hi, is there anything to do with magic value, I have same for all 4 private server.

**Comment by jonatanblockchain** [comment]
Magic vale must be the same for all 4 nodes. 
Are the consensus node's (start consensus) running and 'relaying' blocks? Can you upload an image?

**Comment by VaduganathanPillappan** [comment]
![image](https://user-images.githubusercontent.com/32697208/34441256-83149184-ece0-11e7-8d81-846a2f26638d.png)

**Comment by jonatanblockchain** [comment]
Let' see:
a) You can't connect from neo-gui to the consensus nodes.
b) Consensus process is not running.

Try:

a) Check if ports 10331 to 10334 are open on the 4 consensus nodes.
b) Delete chain folder and peers.dat on one consensus node, and start consensus.
c) Follow the documentation (in Spanish, but you can follow the screenshots) http://docs.neo.org/es-es/node/private-chain.html

**Comment by VaduganathanPillappan** [comment]
I did everything from the beginning, download to install... No luck. same issue.
Thanks for your support, will drop this for now.

**Comment by iamn3rdz** [comment]
![image](https://user-images.githubusercontent.com/29269949/35199131-1fa1d68c-feb7-11e7-839f-3987a3ff8f58.png)
I'm having similar issues. Can't seem to get the 100M Neo from the contract to the address. Heights are also 0/0/0

**Comment by fredrickabhishek** [comment]
@VaduganathanP  ,@iamn3rdz.. I have similar issue similar to what you have both faced.
Here's what you can do. Close the 4 neo-cli node and open neo-gui. then open all the four neo-cli. Open one of the wallet..(make sure your protocol.json and congif .json files are all right). Then you can see the blocks are getting synchronised and they are connected.
