### ISSUE TITLE
Hover-over for AntShares node download address URLs leads to old page

### ISSUE THREAD

**Issue by coranos** [neo-project/docs#33]
on the page:

https://github.com/neo-project/docs/blob/master/en-us/node/introduction.md

When you hover over the links for "The Releases and Source Code" the links go to https://github.com/antshares/ instead of https://github.com/neo-project/

Clicking the link redirects to the correct page, but the hover-over shows the old page.
In contrast, the last link on the page "test network" goes to https://github.com/neo-project/docs/blob/master/en-us/node/testnet.md directly, rather than through a redirect through the old page.

**Comment by Paramon** [comment]
I will change all old links today

**Comment by canesin** [comment]
thanks, we will probably do a regex pass before the rebranding.
