### ISSUE TITLE
I would like to contribute to the translation of the documentation. Where to start?

### ISSUE THREAD

**Issue by obeunda** [neo-project/docs#330]

**Comment by Celia18305** [comment]
You can refer to
[How to contribute to NEO documentation on GitHub.docx](https://github.com/neo-project/docs/files/1634399/How.to.contribute.to.NEO.documentation.on.GitHub.docx)

Let me know if you have more questions.

**Comment by Celia18305** [comment]
You can refer to [How to contribute to NEO documentation on GitHub.pdf](https://github.com/neo-project/docs/files/1634422/How.to.contribute.to.NEO.documentation.on.GitHub.pdf) 

Let me know if you have more questions.
