### ISSUE TITLE
How to use C# to write a NEO smart contract, step 3 fail and no verbose message.

### ISSUE THREAD

**Issue by jphellemons** [neo-project/docs#368]
At http://docs.neo.org/en-us/sc/getting-started-csharp.html#compile-the-project
There is no info how to debug this message, or common pitfalls etc.

````
1>------ Rebuild All started: Project: NeoContract1, Configuration: Debug Any CPU ------
1>  NeoContract1 -> C:\Users\myuser\Documents\Visual Studio 2017\Projects\NeoContract1\NeoContract1\bin\Debug\NeoContract1.dll
1>  Start NeoContract converter, Source File: C:\Users\myuser\Documents\Visual Studio 2017\Projects\NeoContract1\NeoContract1\bin\Debug\NeoContract1.dll
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```` 
Can I manually convert it using neon.exe in order to get a more verbose message? I did update nuget packages before running all the code. ps. the screenshot of the output of neon.exe is a lot more these days.

I also moved neoa, neoj and neon to .net standard 2.0 before build it. But somehow neon.exe outputs version 1.0.1 is that because it uses an outdated neon vm?

**Comment by jphellemons** [comment]
https://steemit.com/neo/@cybourgeoisie/neo-contract-development-common-pitfalls-using-windows-7 says I just had to reboot Windows and restart Visual Studio, but that did not fix it. Is there a commandline option for neon.exe to manually start the contract converter and get a more verbose error?

**Comment by jphellemons** [comment]
Manual run `dotnet build`:
````
NeoContract1.csproj(65,5): error MSB4062: The "Neo.ConvertTask" task could not be loaded from the assembly C:\Users\myuser\Documents\Visual Studio 2017\Projects\NeoContract1\NeoContract1\Neo.ConvertTask.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Het systeem kan het opgegeven bestand niet vinden. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
````

I've added the Microsoft.Build.Utilities.Core nuget but it's in the NEo.ConvertTask.dll and I do not know where that came from? It's probably output of the neo-compiler solution?

**Comment by chenzhitong** [comment]
manually convert it using neon.exe
<img width="563" alt="image" src="https://user-images.githubusercontent.com/6295602/35666246-38d868e0-0764-11e8-9c7d-42212e0ed451.png">

**Comment by chenzhitong** [comment]
I guess the compilation failed because your neon version was too low, you should download the latest neon code to redistribute https://github.com/neo-project/neo-compiler 
The version of NeoContractPlugin will be consistent with neon and NeoVM, if inconsistent there may be a problem of failed compilation, or compilation pass but failure to run. @jphellemons

**Comment by jphellemons** [comment]
````
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found
````
perhaps because I thought .net core 2 was forward compatible and I moved the neon project to 2.0

**Comment by Vimal123** [comment]
@jphellemons 
i get same error, can you please tell me the right solution for this.

Thank you.

**Comment by bobio2018** [comment]
@chenzhitong I ran into a similar build failure for ConvertTask

> 1>Using "ConvertTask" task from assembly "C:\Development\Tutorial\NeoContract\NeoContract\Neo.ConvertTask.dll".
> 1>Task "ConvertTask"
> 1>Done executing task "ConvertTask" -- FAILED.
> 1>Done building target "AfterBuild" in project "NeoContract.csproj" -- FAILED.
> 1>
> 1>Build FAILED.


 I run the compiler manually then it did generate neocontract.abi.json and neocontract.avm . I did download the latest the compiler from https://github.com/neo-project/neo-compiler (Latest commit 9777729  on Jan 14)
below is my compiler version

```
C:\Development\Tutorial\NeoContract\NeoContract\bin\Debug>neon
Neo.Compiler.MSIL console app v2.0.3.1
need one param for DLL filename.

C:\Development\Tutorial\NeoContract\NeoContract\bin\Debug>neon.exe neocontract.dll
Neo.Compiler.MSIL console app v2.0.3.1
Find entrypoint:System.Void NeoContract.Contract1::Main()
convert succ
gen abi succ
write:neocontract.avm
write:neocontract.abi.json
SUCC
```

**Comment by BSathvik** [comment]
I have the same exact problem. Any solutions ?

**Comment by skkiran** [comment]
I had same issue.  Restarting visual studio after adding "directory of neon.exe" into the PATH (as in section 3 of http://docs.neo.org/en-us/sc/getting-started-csharp.html) resolved it.
