### ISSUE TITLE
Using the NEO-GUI Client: Should be more clear about whether the description is for configuring mainnet or testnet

### ISSUE THREAD

**Issue by mwherman2000** [neo-project/docs#382]
Add to a note at the top of the page [http://docs.neo.org/en-us/node/gui.html](http://docs.neo.org/en-us/node/gui.html) to clarify this.

For example, is [https://www.neo.org/client/chain.acc.zip](https://www.neo.org/client/chain.acc.zip) an archive of the mainnet blockchain or testnet blockchain.  I'm assuming the former.  Is there a downloadable archive of the testnet blockchain that should be documented here as well?
Michael Herman (Toronto)

**Comment by Celia18305** [comment]
The document is updated. You can check here: http://docs.neo.org/en-us/node/gui.html
