### ISSUE TITLE
Java tutorial issues with Linux

### ISSUE THREAD

**Issue by ianaz** [neo-project/docs#386]
I'd like to point out some issues I had with following the tutorial for Java on Linux and how I solved. 
I'm using Ubuntu 16.04. Please take this as a discussion point; I'm not a  C# developer so I might have done something wrong, but the documentation should be easy to use for anyone (and I guess you want to support Linux' users as well)

On the first step I had to use another editor as Visual studio 2017 doesn't run on Linux; that means I had to build the project manually by command line
After having installed **dotnet** for Linux, went into /neo-compiler/neoj and run dotnet build I got 

```
$ dotnet run
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.0.4' was not found.
```
to make it work i had to change the neoj.csproj's line with the version I have installed (which was 2.0.5)
`<RuntimeFrameworkVersion>2.0.5</RuntimeFrameworkVersion>`

Created the HelloWorld.java class and compiled to .class with
`javac HelloWorld.java -cp org.neo.smartcontract.framework.jar`

`sudo cp org.neo.smartcontract.framework.jar /usr/share/dotnet`

then

```
$ dotnet run HelloWorld.class
Neo.Compiler.JVM console app v2.0.3.0
Find entrypoint:HelloWorld::Main
convert succ
write:HelloWorld.avm
SUCC
```

All good! 

I can create a PR adding these information if you want

**Comment by anfn101** [comment]
Please go ahead with that @ianaz

**Comment by ianaz** [comment]
Created PR #396

**Comment by ianaz** [comment]
Merged
