### ISSUE TITLE
Can't able to see NEP-5 based asset Via neo-cl

### ISSUE THREAD

**Issue by KanishTheVista** [neo-project/docs#405]

**Comment by KanishTheVista** [comment]
Dealing with User Withdrawals
The exchange can choose one of the following way to send NEP-5 assets to users:

NEO-CLI command: send

RPC method: sendtoaddress

PRC method: sendmany

NEO-CLI Command: send
Syntax
send <txid|script hash> <address> <value> [fee = 0]
This is mentioned in doc but to execute above command asset must be listed

**Comment by Celia18305** [comment]
We added a FAQ to clarify: https://docs.neo.org/faq/en-us/dev.html#e1e438f8
