### ISSUE TITLE
How to transfer NEO from a smart contract address to other addresses programmingly?

### ISSUE THREAD

**Issue by blockchain1977** [neo-project/docs#429]
Hello,

I would like to achieve below function:
When NEO was trasfered from other address to my smart contract address, the smart contract transfer the NEO to other address automatically. How can I do such thing? I didn't find any info in current documentation. Thanks!

**Comment by Celia18305** [comment]
It is not supported. You cannot transfer global assets like NEO, GAS in the smart contract.

**Comment by cars0nhk** [comment]
How about NEP5?

Thanks
