### ISSUE TITLE
如何把nep5日志里面的scripthash地址转换成neo地址

### ISSUE THREAD

**Issue by lanmp** [neo-project/docs#473]
http://docs.neo.org/zh-cn/exchange/v2.7.3.html
对于转账交易，"state" 中 "value" 对应的数组包含以下四个对象：

[事件，转出账户，转入账户，金额]

数组中的第一个对象，类型为bytearray，值为"7472616e73666572"，经过转换，为字符串"transfer"。transfer是 NEP-5 中的一个方法，代表资产转账。

{
"type": "ByteArray",
"value": "7472616e73666572"
}
数组中的的第二个对象，为转出账户地址，类型为bytearray，值为"9393ee15ce6612484ab5be3bbc78c82af8dc0e07"，经过转换，为字符串 "AVECC4AcGXfDjm7cGmfGuxVRGTu6FxoQ7h"。

这里这里两个值如何转换？文档里面说的不太清楚

**Comment by chenzhitong** [comment]
@lanmp 以下是将ScriptHash转为地址的C#代码，引入了NEO的SDK，
var hex = "9393ee15ce6612484ab5be3bbc78c82af8dc0e07".HexToBytes().Reverse().ToHexString();
var scriptHash = UInt160.Parse(hex);
var address = Neo.Wallets.Wallet.ToAddress(scriptHash);
Console.WriteLine(address);
