### ISSUE TITLE
[error] the docs error in chinese version

### ISSUE THREAD

**Issue by Cody1988** [neo-project/docs#486]
there are some error in home page 。please fix it , of course I can push a pr , if it is encouraged .

1. [智能合约部署](http://docs.neo.org/zh-cn/sc/quickstart/deploy-invoke.html), in this page, the png file is missed;

2. [合约编写限制](http://docs.neo.org/zh-cn/sc/quickstart/limitation.md), this link is missed;

3. [智能合约触发器](http://docs.neo.org/zh-cn/sc/trigger.md), this link is missed;

**Comment by Celia18305** [comment]
These docs are in the process of editing. I will fix them soon. Thanks for your concern.

**Comment by Celia18305** [comment]
部署和调用：http://docs.neo.org/zh-cn/sc/quickstart/deploy-invoke.html
合约编写须知：http://docs.neo.org/zh-cn/sc/quickstart/notices.html
合约触发器：http://docs.neo.org/zh-cn/sc/trigger.html
