### ISSUE TITLE
Distribution error in document

### ISSUE THREAD

**Issue by marcel-burkhard** [neo-project/docs#50]
Referring to: https://github.com/neo-project/docs/blob/master/en-us/index.md

>In the first year (actually 0-200 million blocks), each block will generate 8 new GAS; in the second year (actually the first 200-400 million blocks), each new block will generate 7 GAS and so on. There will be an annual reduction of 1 GAS for the first 8 years until 1 GAS per block is reached; this will be the rate of GAS generation until about 22 years, after the 44 millionth block, GAS total will reach 100 million, thus stopping the generation of GAS from new blocks.

I think it need so to be as follows (replaced 0-200, 200-400 with 0-2, 2-4):
>In the first year (actually 0-2 million blocks), each block will generate 8 new GAS; in the second year (actually the first 2-4 million blocks), each new block will generate 7 GAS and so on. There will be an annual reduction of 1 GAS for the first 8 years until 1 GAS per block is reached; this will be the rate of GAS generation until about 22 years, after the 44 millionth block, GAS total will reach 100 million, thus stopping the generation of GAS from new blocks.

Otherwise it would be contradicting:
>In the first year (actually 0-200 million blocks)
-----
>after the 44 millionth block, GAS total will reach 100 million, thus stopping the generation of GAS from new blocks

Please fix, thanks. :-)

Is the following information correct?
- Block # <   2'000'000 = 8
- Block # <   4'000'000 = 7
- Block # <   6'000'000 = 6
- Block # <   8'000'000 = 5
- Block # < 10'000'000 = 4
- Block # < 12'000'000 = 3
- Block # < 14'000'000 = 2
- Block # < 44'000'000 = 1
- Block # > 44'000'000 = 0

**Comment by CJSS** [comment]
Pull request #54 has been added with the changes to the nunmbers you have mentioned.
