### ISSUE TITLE
RPC NOT WORKING 

### ISSUE THREAD

**Issue by KanishTheVista** [neo-project/docs#589]
when i was using
curl -X POST http://localhost:10332/ -H 'Content-Type: application/json' -d '{ "jsonrpc": "2.0", "id": 5, "method": "getblocksysfee", "params": [13321] }'
its saying
curl: (7) Failed to connect to localhost port 10332: Connection refused
my neo-cli node is running rpc flag
is there any issues with neo-cli

**Comment by superboyiii** [comment]
@KanishTheVista  Be sure your offline sync has completed. During the sync by offline package, your neo-cli will not communicate with any request and the node seems 0. When the use of package has been completed, there'll be numbers on nodes. Then rpc will be fine.
