### ISSUE TITLE
[Question] list asset for cli api

### ISSUE THREAD

**Issue by vladyslavstartsev** [neo-project/docs#662]
Hi! Is there a way to get  result of `list asset` (the cli command) on the cli api?

**Comment by Celia18305** [comment]
You can use the getbalance API (http://docs.neo.org/en-us/node/cli/2.9.0/api/getbalance.html)

**Comment by vladyslavstartsev** [comment]
@Celia18305 thanks for the answer!
Yes, but what I need is to list all the assets that I have on my wallet, that is why I need `list asset`.
In `getbalance` you also need the asset_id, but what I don't have the asset id's?
How can I list all asset ids on API?

**Comment by Celia18305** [comment]
@vladyslavstartsev Actually "list asset" can list only UTXO assets like NEO and GAS, getbalance lists all the assets.  For asset ids information:
 NEO：c56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b
GAS: 02c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7
Other assets look up here: https://scan.nel.group/zh/#mainnet/assets

**Comment by vladyslavstartsev** [comment]
thanks!

Actually it will be nice feature to have, 
1.to get all balances by all assets
2. list all assets that I have on my wallet
