### ISSUE TITLE
Some suggestions on NEO-Python docs

### ISSUE THREAD

**Issue by nicolegys** [neo-project/docs#666]
1./安装（Ubuntu/OSX）
从Git安装
“(venv) pip install -e”改成“(venv) pip install -e .”
2./安装（Windows）
遗漏一句“Another option is to setup a Linux Subsystem with Ubuntu (see also here for more infos and a guide).”，显得下面的NOTE有些突兀。
3./NEO-Python SeedList
更新 Windows WSL (Ubuntu) 上的 NEO-Python 节点列表
“你需要修改 lib/python3.6/site-packages/neo/data路径下 venv 目录里的 protocol.mainnet.json 文件”改为“你需要修改 venv 目录里lib/python3.6/site-packages/neo/data路径下的 protocol.mainnet.json 文件”。
4./设置和日志
“日志文件（可选择旋转）”改为“日志文件（可切换）”
“neo-python 使用 logzero 进行记录。要在现有的neo日志记录配置中使用alogger，只需从logzero导入日志记录器”改为”neo-python 使用 logzero 进行记录。要在现有的neo日志记录配置中使用logger，只需从logzero导入logger“
5./与智能合约交互
![image](https://user-images.githubusercontent.com/43694095/48053956-ee355380-e1e6-11e8-992d-524dffd722ba.png)
tx_hash是交易散列值

**Comment by Celia18305** [comment]
Fixed in PR #668
