### ISSUE TITLE
Add extra info (about backup) to "Document for Exchange Developers"

### ISSUE THREAD

**Issue by vladyslavstartsev** [neo-project/docs#671]
Hi! 
It is not clear for me what section on address generation mean.

What I did is 
- loaded one node
- sync
- created wallet1
- generate address with CLI API
- generate address with CLI daemon
- buy and send 1 NEO and send to generated address (API)
-  get other server, load second node
- export wallet1
- import wallet1 to second node
- sync
- and I got my 1 NEO, because it writes new address in wallet.json (NEP6) 

but it doesn't write addresses to wallet that was imported with address.txt 
what I mean
- generate addresses (api and daemon) on the first node
- export them
- import them to second node

this was not clear at all

please make that NEO CLI can write addresses to wallet.json (NEP6) and make it clear in the docs what can/can't be exported/imported

**Comment by Celia18305** [comment]
Updated the doc in PR #672
