### ISSUE TITLE
Docs don't reflect that GAS can't be claimed for unclaimed NEO

### ISSUE THREAD

**Issue by devhawk** [neo-project/docs#791]
As per the [FAQ](https://docs.neo.org/en-us/faq.html), you cannot claim GAS until NEO has been spent. 

> **What is GAS？How to acquire GAS？**
> GAS represents the right to use the Neo Blockchain. NEO network charges GAS for the new assets issuance as well as for smart contract running and storage. In the genesis block GAS is 0 and it is generated as new blocks generate. Once NEO is acquired, GAS is generated in the system following the algorithms. GAS has two status, available and unavailable. Once NEO is spent (i.e. transferred out) from the account, the relevant GAS turns to available. NEO holders can initiate a claim transaction at any time to claim available GAS to the NEO address.

> **Can I transfer GAS to my own account to make it claimable?**
> Yes. You can do that even if there is just one address in your wallet.

However, this information should also be a part of any official docs related to claiming GAS, such as [Build a Private Chain](https://docs.neo.org/en-us/network/private-chain/private-chain.html#transferring-gas-to-a-normal-address)

I filed an [issue on neo-cli](https://github.com/neo-project/neo-cli/issues/331) originally, but this appears to be a docs issue.

**Comment by Celia18305** [comment]
Fixed in #793.
