### ISSUE TITLE
update doc to 2.10.2

### ISSUE THREAD

**Issue by Celia18305** [neo-project/docs#813]

**Comment by Celia18305** [comment]
Pls give input for how the doc should be updated. Thanks.

**Comment by superboyiii** [comment]
计价模型修改：
1.	对于除 ClaimTransaction 以外的资产交易，在交易大小超过1024byte的情况下，会按 交易的大小*0.00001gas + 0.001gas 的起始费用来收取额外的网络手续费。 如用户已在交易中添加自定义网络手续费，则按两者中价格最高的一方作为实际网络手续费加入交易中。收取网络手续费的根本目的是在于阻止恶意交易与网络攻击，在当前机制下，对于普通用户的正常交易一般不会造成额外手续费的负担。
2.	对于在主网发布或调用合约（上链交易），会征收 0.001gas 的初始费用。如交易大小超过1024byte，会额外征收交易的大小*0.00001gas的网络手续费。
3.	对于使用RPC来发送交易的用户，当前版本在 RpcWallet 插件中提供了名为 config.json 的配置文件来自定义自愿缴纳手续费的上限。 如用户触发了收取手续费的条件，配置文件会对用户资产提供保护，使在自定义上限范围内手续费的交易正常上链。而超过自定义上限范围手续费的交易则会失败。

**Comment by superboyiii** [comment]
需要新增rpc:
1. getmetricblocktimestamp
params: blocks numbers
params: endHeight

sample
request:
{
  "jsonrpc": "2.0",
  "method": "getmetricblocktimestamp",
  "params": [10, 460000],
  "id": 1
}

response:
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": [
        {
            "timestamp": 1556138776,
            "height": 459990
        },
        {
            "timestamp": 1556138791,
            "height": 459991
        },
        {
            "timestamp": 1556138822,
            "height": 459992
        },
        {
            "timestamp": 1556138839,
            "height": 459993
        },
        {
            "timestamp": 1556138854,
            "height": 459994
        },
        {
            "timestamp": 1556138869,
            "height": 459995
        },
        {
            "timestamp": 1556138902,
            "height": 459996
        },
        {
            "timestamp": 1556138917,
            "height": 459997
        },
        {
            "timestamp": 1556138932,
            "height": 459998
        },
        {
            "timestamp": 1556138947,
            "height": 459999
        },
        {
            "timestamp": 1556138981,
            "height": 460000
        }
    ]
}

2. getclaimable
返回可以claim的gas内容
params: address
sample:

request:
{
  "jsonrpc": "2.0",
  "method": "getclaimable",
  "params": ["AGofsxAUDwt52KjaB664GYsqVAkULYvKNt"],
  "id": 1
}

response:
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "claimable": [
            {
                "txid": "52ba70ef18e879785572c917795cd81422c3820b8cf44c24846a30ee7376fd77",
                "n": 1,
                "value": 800000,
                "start_height": 476496,
                "end_height": 488154,
                "generated": 746.112,
                "sys_fee": 3.92,
                "unclaimed": 750.032
            }
        ],
        "address": "AGofsxAUDwt52KjaB664GYsqVAkULYvKNt",
        "unclaimed": 750.032
    }
}

3. getunclaimed
返回未claim的gas内容
params: address
sample:

request:
{
  "jsonrpc": "2.0",
  "method": "getunclaimed",
  "params": ["AGofsxAUDwt52KjaB664GYsqVAkULYvKNt"],
  "id": 1
}

response:
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "available": 750.032,
        "unavailable": 2815.408,
        "unclaimed": 3565.44
    }
}

4.getunspents
返回未花费的UTXO信息
params: address
sample:

request:
{
  "jsonrpc": "2.0",
  "method": "getunspents",
  "params": ["AGofsxAUDwt52KjaB664GYsqVAkULYvKNt"],
  "id": 1
}

response:
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "balance": [
            {
                "unspent": [
                    {
                        "txid": "4ee4af75d5aa60598fbae40ce86fb9a23ffec5a75dfa8b59d259d15f9e304319",
                        "n": 0,
                        "value": 27844.821
                    },
                    {
                        "txid": "9906bf2a9f531ac523aad5e9507bd6540acc1c65ae9144918ccc891188578253",
                        "n": 0,
                        "value": 0.987
                    },
                    {
                        "txid": "184e34eb3f9550d07d03563391d73eb6c438130c7fdca37f0700d5d52ad7deb1",
                        "n": 0,
                        "value": 243.95598
                    },
                    {
                        "txid": "448abc64412284fb21c9625ac9edd2100090367a551c18ce546c1eded61e77c3",
                        "n": 0,
                        "value": 369.84904
                    },
                    {
                        "txid": "bd454059e58da4221aaf4effa3278660b231e9af7cea97912f4ac5c4995bb7e4",
                        "n": 0,
                        "value": 600.41014479
                    }
                ],
                "asset_hash": "602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7",
                "asset": "GAS",
                "asset_symbol": "GAS",
                "amount": 29060.02316479
            },
            {
                "unspent": [
                    {
                        "txid": "c3182952855314b3f4b1ecf01a03b891d4627d19426ce841275f6d4c186e729a",
                        "n": 0,
                        "value": 800000
                    }
                ],
                "asset_hash": "c56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b",
                "asset": "NEO",
                "asset_symbol": "NEO",
                "amount": 800000
            }
        ],
        "address": "AGofsxAUDwt52KjaB664GYsqVAkULYvKNt"
    }
}

**Comment by superboyiii** [comment]
command line更新：
plugins
例子：
neo> Plugins
Loaded plugins:
        RpcSystemAssetTrackerPlugin
        RpcNep5Tracker
        RpcSecurity
        StatesDumper
        CoreMetrics
        ImportBlocks
        RpcWallet
        ApplicationLogs
        SimplePolicyPlugin

**Comment by Celia18305** [comment]
PR #816
