### ISSUE TITLE
update Lock Contract Tutorial

### ISSUE THREAD

**Issue by wanglongfei88** [neo-project/docs#851]
There are two pages for Lock Contract examples: 
1,  Smart Contract -> Smart Contract Example -> Smart Contract Example - Lock (Lock Contract)
2,  Smart Contract -> Smart Contract Example -> Smart Contract Example - Lock Contract Tutorial

And those two pages show different code for lock contract, can we please combine them and use one working example ?

**Comment by Celia18305** [comment]
Fixed in #853
