### ISSUE TITLE
Remove irrelevant pages about python nodes

### ISSUE THREAD

**Issue by Ashuaidehao** [neo-project/docs#863]
In python docs(https://docs.neo.org/zh-cn/node/python/overview.html) ,there are many irrelevant pages.

![WeChat Photo Editor_20190708140651](https://user-images.githubusercontent.com/7391819/60786630-d6eda200-a189-11e9-8364-21c79499dfb8.jpg)

Can we remove them？These pages are related to SDK or SmartContract.

**Comment by Celia18305** [comment]
Fixed:https://docs.neo.org/docs/zh-cn/node/python/overview.html
