### ISSUE TITLE
Several URL Link redirect to english version page while current page is Chinese version

### ISSUE THREAD

**Issue by cloud8little** [neo-project/docs#864]
here https://docs.neo.org/developerguide/zh/articles/introduction.html there are several URL redirect link, it redirects to english version by default.￼
![屏幕快照 2019-07-08 下午6 58 37](https://user-images.githubusercontent.com/34291844/60805522-f0571400-a1b2-11e9-9e4e-e2992b9ab693.png)
￼
![1562583805995](https://user-images.githubusercontent.com/34291844/60805613-27c5c080-a1b3-11e9-8396-18b7a0f9d989.jpg)

￼

**Comment by Celia18305** [comment]
The entire content of developer guide has been merged into https://docs.neo.org/docs/zh-cn/index.html (NEO tool development). We won't maintain the old repository any more. So close this bug.
