### ISSUE TITLE
hyperlink deploy-invoke for neo-gui is out-of-date

### ISSUE THREAD

**Issue by cloud8little** [neo-project/docs#866]
hyperlink https://docs.neo.org/zh-cn/sc/quickstart/deploy-invoke.md for (部署和调用智能合约) https://docs.neo.org/zh-cn/node/gui/sc.html   is out-of-date

**Comment by Celia18305** [comment]
Fixed. Check here: https://docs.neo.org/docs/zh-cn/node/gui/sc.html
