### ISSUE TITLE
[Suggestion] Improve FAQ part

### ISSUE THREAD

**Issue by cloud8little** [neo-project/docs#867]
Can we have all these questions on portal FAQ too?  because they are valuable questions.   
https://github.com/CityOfZion/awesome-neo/blob/master/resources/faq.md

**Comment by Celia18305** [comment]
Sure. Will merge that portion soon. Thanks!

**Comment by corollari** [comment]
If possible I'd hold off on including these questions, as many of them are outdated. Currently I'm working on updating the FAQ.

**Comment by cloud8little** [comment]
> If possible I'd hold off on including these questions, as many of them are outdated. Currently I'm working on updating the FAQ.

some are outdated, while still there are some valuable questions, such as question #3,#4,#6, #13, and also they are the questions exchange frequently asked us. so i suggest to add them.

**Comment by Celia18305** [comment]
@cloud8little @corollari Hi guys, I merged majority of questions and update some outdated info. Please review and comment in this PR: #899

**Comment by corollari** [comment]
Cool, should we close this then?
