### ISSUE TITLE
Suggestions on docs

### ISSUE THREAD

**Issue by wanglongfei88** [neo-project/docs#882]
I have some suggestions on tech docs:

1. [NEO-CLI命令参考](https://docs.neo.org/docs/zh-cn/node/cli/cli.html)
     * Can we update the title for its navigation? change is to "命令参考”。
     * For Chinese version, can we unify 命令、指令、操作 to 指令？

2. [智能合约 测试](https://docs.neo.org/docs/zh-cn/sc/test.html)
    * It is not unit test for smart contract. Can we change title to "Testing Smart Contract" and "智能合约测试”

3. [API Reference](https://docs.neo.org/docs/zh-cn/reference/rpc/latest-version/api.html)
    * For Chinese version, we should keep it chinese. Should we update the navigation bar to "API 参考"?

4. [Consensus](https://docs.neo.org/docs/zh-cn/basic/technology/dbft.html)
    * dbft 2.0 is already release along with neo-cli 2.10.2 and MainNet nodes are updates. So can we update consensus docs to dbft 2.0?

**Comment by Celia18305** [comment]
Fixed in #894 and #895
