### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by ixje** [neo-project/docs#979]
https://docs.neo.org/docs/en-us/index.html
The search box in the left menu is not functional. No matter what you enter in there, is always says "No results found".

**Comment by chenzhitong** [comment]
![image](https://user-images.githubusercontent.com/6295602/70015375-22c93980-15b8-11ea-96c0-b4da7b8ac9fe.png)

It‘s OK in my computer, what's your OS and browser.

**Comment by ixje** [comment]
OSX, latest Chrome browser. Turned off Add Blocker just to be sure, still no luck.

![Screenshot 2019-12-03 at 08 18 25](https://user-images.githubusercontent.com/6625537/70028725-b6453f00-15a5-11ea-8d8e-8faad4ed2557.png)

**Comment by ixje** [comment]
I've got another person to validate if the search is working for him on OSX + Chrome and it does, so I'm closing this and blame it on some unknown issue on my side.
